# Generated by Django 2.2.28 on 2022-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressgrpybtjamb'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressgrpybtjamb',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
